"""Official Saudi regulatory source registry (config-driven, modular).

Adding a new authority or document requires ONLY adding an entry here (or to the
optional external JSON file at ) — no application-logic changes.

Every URL below points to an OFFICIAL Saudi government source and was verified to
return a real PDF (HTTP 200 + application/pdf). Sources behind an anti-bot WAF
(e.g. SDAIA/CST) are fetched with browser headers by the downloader; any source
that cannot be retrieved is reported honestly by the ingestion pipeline — never
fabricated.
"""
from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass, field
from typing import List

from app.core.config import settings


@dataclass
class SourceDoc:
    id: str
    authority: str            # DGA | NCA | NDMO | PDPL | CST | ...
    authority_name_ar: str
    title_en: str
    title_ar: str
    url: str                  # official direct file URL
    landing_url: str          # official human page (provenance)
    version: str
    published_date: str       # YYYY-MM or YYYY-MM-DD (official)
    language: str             # ar | en | bilingual
    category: str

    def to_dict(self) -> dict:
        return asdict(self)


REGISTRY: List[SourceDoc] = [
    # ===================== NCA — National Cybersecurity Authority =====================
    SourceDoc(
        id='nca-ecc-2-2024-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Essential Cybersecurity Controls (ECC-2:2024)',
        title_ar='الضوابط الأساسية للأمن السيبراني (ECC-2:2024)',
        url='https://cdn.nca.gov.sa/api/files/public/upload/86e09090-44e4-481f-bc28-355673607654_ECC--2024-EN.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/ecc/',
        version='2:2024',
        published_date='2024-09',
        language='en',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-ecc-2-2024-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Essential Cybersecurity Controls (ECC-2:2024) — Arabic',
        title_ar='الضوابط الأساسية للأمن السيبراني (ECC-2:2024)',
        url='https://cdn.nca.gov.sa/api/files/public/upload/e4c81aa9-a609-4823-abab-347283e29731_ECC-2-2024-AR-19092024-.pdf',
        landing_url='https://nca.gov.sa/regulatory-documents/controls-list/ecc/',
        version='2:2024',
        published_date='2024-09',
        language='ar',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-ecc-impl-guide',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Guide to Essential Cybersecurity Controls (ECC) Implementation',
        title_ar='دليل تطبيق الضوابط الأساسية للأمن السيبراني',
        url='https://cdn.nca.gov.sa/api/public/cms/files/fd4cfde4-6ffe-45d5-ac29-820e4d2e4ef0_Guide-to-Essential-Cybersecurity-Controls-(ECC)-Implementation.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/guidelines-list/gecc/',
        version='latest',
        published_date='2024',
        language='en',
        category='cybersecurity_guide',
    ),
    SourceDoc(
        id='nca-ccc-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Cloud Cybersecurity Controls (CCC)',
        title_ar='ضوابط الأمن السيبراني للحوسبة السحابية',
        url='https://nca.gov.sa/ccc-en.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/ccc/',
        version='1:2020',
        published_date='2020',
        language='en',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-ccc-2-2024-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Cloud Cybersecurity Controls (CCC-2:2024)',
        title_ar='ضوابط الأمن السيبراني للحوسبة السحابية',
        url='https://cdn.nca.gov.sa/api/files/public/upload/bd85b958-45a7-4b65-8eb1-cc1361c91233_CCC-2-2024-.pdf',
        landing_url='https://nca.gov.sa/ar/regulatory-documents/controls-list/ccc/',
        version='2:2024',
        published_date='2024',
        language='ar',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-ccc-methodology-annex-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Cloud Cybersecurity Controls Methodology and Mapping Annex (CCC-1:2020)',
        title_ar='ملحق المنهجية والمواءمة لضوابط الأمن السيبراني للحوسبة السحابية',
        url='https://nca.gov.sa/ccc_methodology_and_mapping_annex_en.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/ccc/',
        version='1:2020',
        published_date='2020',
        language='en',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-ccc-csp-guideline-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Guide to Cloud Cybersecurity Controls - CSP Implementation Guideline',
        title_ar='الدليل الإرشادي لتطبيق ضوابط الأمن السيبراني للحوسبة السحابية لمقدمي الخدمات',
        url='https://cdn.nca.gov.sa/api/public/cms/files/eea788f1-949f-46a1-bc9b-a154c26059df_CCC_CSP_Implementation_Guideline_en-.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/ccc/',
        version='1:2020',
        published_date='2020',
        language='en',
        category='implementation_guideline',
    ),
    SourceDoc(
        id='nca-ccc-cst-guideline-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Guide to Cloud Cybersecurity Controls - CST Implementation Guideline',
        title_ar='الدليل الإرشادي لتطبيق ضوابط الأمن السيبراني للحوسبة السحابية للمشتركين',
        url='https://cdn.nca.gov.sa/api/files/public/upload/1c46a45e-7d51-4493-bd96-53ec94980368_CCC_CST_Implementation_Guideline_en-.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/ccc/',
        version='1:2020',
        published_date='2020',
        language='en',
        category='implementation_guideline',
    ),
    SourceDoc(
        id='nca-ccc-cst-guideline-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Guide to Cloud Cybersecurity Controls - CST Implementation Guideline (AR)',
        title_ar='الدليل الإرشادي لتطبيق ضوابط الأمن السيبراني للحوسبة السحابية للمشتركين',
        url='https://cdn.nca.gov.sa/api/files/public/upload/96663229-7b3f-4a26-8858-cc69d4eb6966_CCC_CST_Implementation_Guideline_ar.pdf',
        landing_url='https://nca.gov.sa/ar/regulatory-documents/controls-list/ccc/',
        version='1:2020',
        published_date='2020',
        language='ar',
        category='implementation_guideline',
    ),
    SourceDoc(
        id='nca-cscc-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Critical Systems Cybersecurity Controls (CSCC-1:2019)',
        title_ar='ضوابط الأمن السيبراني للأنظمة الحساسة',
        url='https://cdn.nca.gov.sa/api/files/public/upload/f15af01c-dc59-4281-95e2-03a770655937_Critical-Systems-Cybersecurity-Controls.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/cscc/',
        version='1:2019',
        published_date='2019',
        language='en',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-cscc-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Critical Systems Cybersecurity Controls (CSCC-1:2019) (AR)',
        title_ar='ضوابط الأمن السيبراني للأنظمة الحساسة',
        url='https://nca.gov.sa/cscc-ar.pdf',
        landing_url='https://nca.gov.sa/ar/regulatory-documents/controls-list/cscc/',
        version='1:2019',
        published_date='2019',
        language='ar',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-otcc-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Operational Technology Cybersecurity Controls (OTCC-1:2022)',
        title_ar='ضوابط الأمن السيبراني للأنظمة التشغيلية',
        url='https://nca.gov.sa/otcc_en.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/otcc/',
        version='1:2022',
        published_date='2022',
        language='en',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-otcc-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Operational Technology Cybersecurity Controls (OTCC-1:2022) (AR)',
        title_ar='ضوابط الأمن السيبراني للأنظمة التشغيلية',
        url='https://nca.gov.sa/otcc_ar.pdf',
        landing_url='https://nca.gov.sa/ar/regulatory-documents/controls-list/otcc/',
        version='1:2022',
        published_date='2022',
        language='ar',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-otcc-methodology-annex-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='OTCC Methodology and Mapping Annex (OTCC-1:2022)',
        title_ar='ملحق المنهجية والمواءمة لضوابط الأمن السيبراني للأنظمة التشغيلية',
        url='https://cdn.nca.gov.sa/api/files/public/upload/071d52fc-014b-4f15-84ce-1289f3f5c3a9_Operational-Technology-Cybersecurity-Controls-Methodogy-and-Mapping-Annex.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/otcc/',
        version='1:2022',
        published_date='2022',
        language='en',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-otcc-methodology-annex-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='OTCC Methodology and Mapping Annex (OTCC-1:2022) (AR)',
        title_ar='ملحق المنهجية والمواءمة لضوابط الأمن السيبراني للأنظمة التشغيلية',
        url='https://cdn.nca.gov.sa/api/files/public/upload/6e58f002-1031-4116-b1d4-fd26c9840e7d_ملحق-المنهجية-والمواءمة-لضوابط-الأمن-السيبراني-للأنظمة-التشغيلية-.pdf',
        landing_url='https://nca.gov.sa/ar/regulatory-documents/controls-list/otcc/',
        version='1:2022',
        published_date='2022',
        language='ar',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-tcc-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Telework Cybersecurity Controls (TCC-1:2021)',
        title_ar='ضوابط الأمن السيبراني للعمل عن بعد',
        url='https://nca.gov.sa/telework_cybersecurity_controls-en.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/tcc/',
        version='1:2021',
        published_date='2021',
        language='en',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-tcc-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Telework Cybersecurity Controls (TCC-1:2021) (AR)',
        title_ar='ضوابط الأمن السيبراني للعمل عن بعد',
        url='https://nca.gov.sa/Telework-Cybersecurity-Controls.pdf',
        landing_url='https://nca.gov.sa/ar/regulatory-documents/controls-list/tcc/',
        version='1:2021',
        published_date='2021',
        language='ar',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-dcc-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Data Cybersecurity Controls (DCC-1:2022)',
        title_ar='ضوابط الأمن السيبراني للبيانات',
        url='https://cdn.nca.gov.sa/api/files/public/upload/1c2cfb9c-7788-4549-9f29-f337500f1787_Data-Cybersecurity-Controls-.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/dcc/',
        version='1:2022',
        published_date='2022',
        language='en',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-dcc-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Data Cybersecurity Controls (DCC-1:2022) (AR)',
        title_ar='ضوابط الأمن السيبراني للبيانات',
        url='https://cdn.nca.gov.sa/api/files/public/upload/32bf3911-3c6d-4802-af66-773c2174aee5_DCC-.pdf',
        landing_url='https://nca.gov.sa/ar/regulatory-documents/controls-list/dcc/',
        version='1:2022',
        published_date='2022',
        language='ar',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-osmacc-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en="Organizations' Social Media Accounts Cybersecurity Controls (OSMACC-1:2023)",
        title_ar='ضوابط الأمن السيبراني لحسابات التواصل الاجتماعي للجهات',
        url='https://nca.gov.sa/osmacc-en.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/osmacc/',
        version='1:2023',
        published_date='2023',
        language='en',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-osmacc-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en="Organizations' Social Media Accounts Cybersecurity Controls (OSMACC-1:2023) (AR)",
        title_ar='ضوابط الأمن السيبراني لحسابات التواصل الاجتماعي للجهات',
        url='https://nca.gov.sa/OSMACC.pdf',
        landing_url='https://nca.gov.sa/ar/regulatory-documents/controls-list/osmacc/',
        version='1:2023',
        published_date='2023',
        language='ar',
        category='cybersecurity_controls',
    ),
    SourceDoc(
        id='nca-osmacc-guideline-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Guide to OSMACC Implementation',
        title_ar='الدليل الإرشادي لتطبيق ضوابط الأمن السيبراني لحسابات التواصل الاجتماعي للجهات',
        url='https://cdn.nca.gov.sa/api/public/cms/files/39576bb2-7851-454d-a60a-998a1f5ed6ab_OSMACC_Implementation-Guideline_en.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/osmacc/',
        version='1:2023',
        published_date='2023',
        language='en',
        category='implementation_guideline',
    ),
    SourceDoc(
        id='nca-gecc-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Guide to Essential Cybersecurity Controls (ECC) Implementation (GECC)',
        title_ar='الدليل الإرشادي لتطبيق الضوابط الأساسية للأمن السيبراني',
        url='https://cdn.nca.gov.sa/api/files/public/upload/11bb8f2d-706a-4f18-80f1-40d620ebd845_GECC-.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/controls-list/ecc/',
        version='1:2020',
        published_date='2020',
        language='en',
        category='implementation_guideline',
    ),
    SourceDoc(
        id='nca-gecc-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='Guide to Essential Cybersecurity Controls (ECC) Implementation (GECC) (AR)',
        title_ar='الدليل الإرشادي لتطبيق الضوابط الأساسية للأمن السيبراني',
        url='https://cdn.nca.gov.sa/ar/Guide_to_Essential_Cybersecurity_Controls_Implementation.pdf',
        landing_url='https://nca.gov.sa/ar/regulatory-documents/controls-list/ecc/',
        version='1:2020',
        published_date='2020',
        language='ar',
        category='implementation_guideline',
    ),
    SourceDoc(
        id='nca-ncs-1-2020-en',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='National Cryptographic Standards (NCS-1:2020)',
        title_ar='المعايير الوطنية للتشفير',
        url='https://nca.gov.sa/ncs_en.pdf',
        landing_url='https://nca.gov.sa/en/regulatory-documents/frameworks-and-standard-list/ncs/',
        version='1:2020',
        published_date='2020',
        language='en',
        category='frameworks_and_standards',
    ),
    SourceDoc(
        id='nca-ncs-1-2020-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='National Cryptographic Standards (NCS-1:2020) (AR)',
        title_ar='المعايير الوطنية للتشفير',
        url='https://nca.gov.sa/ncs_ar.pdf',
        landing_url='https://nca.gov.sa/ar/regulatory-documents/frameworks-and-standard-list/national-cryptographic-standards-ar/',
        version='1:2020',
        published_date='2020',
        language='ar',
        category='frameworks_and_standards',
    ),
    SourceDoc(
        id='nca-ncs-2-2025-ar',
        authority='NCA',
        authority_name_ar='الهيئة الوطنية للأمن السيبراني',
        title_en='National Cryptographic Standards (NCS-2:2025)',
        title_ar='المعايير الوطنية للتشفير',
        url='https://cdn.nca.gov.sa/api/files/public/upload/22ec7618-3d9a-4f04-994e-9ff77f5d1146_NCS-2-ar---Copy.pdf',
        landing_url='https://nca.gov.sa/ar/regulatory-documents/frameworks-and-standard-list/national-cryptographic-standards-ar/',
        version='2:2025',
        published_date='2025',
        language='ar',
        category='frameworks_and_standards',
    ),
    # ===================== DGA — Digital Government Authority =====================
    SourceDoc(
        id='dga-regulatory-framework-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Digital Government Regulatory Framework',
        title_ar='الإطار التنظيمي للحكومة الرقمية',
        url='https://dga.gov.sa/sites/default/files/2022-08/Digital%20Government%20Regulatory%20Framework%20%E2%80%93%20V1.0_0.pdf',
        landing_url='https://dga.gov.sa/en/regulatory_framework/controls-and-standards-overview',
        version='1.0',
        published_date='2021-08',
        language='en',
        category='digital_government_framework',
    ),
    SourceDoc(
        id='dga-digital-government-policies-v2',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Digital Government Policies',
        title_ar='سياسات الحكومة الرقمية',
        url='https://dga.gov.sa/sites/default/files/2024-03/Digital%20Government%20Policies%20-%20V2.0.pdf',
        landing_url='https://dga.gov.sa/en/regulatory-documents/Digital-government-policies',
        version='2.0',
        published_date='2024-03',
        language='en',
        category='digital_government_policies',
    ),
    SourceDoc(
        id='dga-digital-transformation-standards-v4',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Digital Transformation Basic Standards',
        title_ar='المعايير الأساسية للتحول الرقمي',
        url='https://dga.gov.sa/sites/default/files/2025-12/Digital%20Transformation%20Basic%20Standards%20-%20V4.0.pdf',
        landing_url='https://dga.gov.sa/en/Standards_Of_Digital_Transformation',
        version='4.0',
        published_date='2025-12',
        language='en',
        category='digital_transformation_standards',
    ),
    SourceDoc(
        id='dga-it-governance-controls-v3',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Controls for Information Technology Governance in Digital Government',
        title_ar='ضوابط حوكمة تقنية المعلومات في الحكومة الرقمية',
        url='https://dga.gov.sa/sites/default/files/2026-06/Controls%20for%20Information%20Technology%20Governance%20in%20Digital%20Government-V3.0_0.pdf',
        landing_url='https://dga.gov.sa/en/regulatory-documents/IT-governance-controls-in-digital-government',
        version='3.0',
        published_date='2026',
        language='en',
        category='digital_government_controls',
    ),
    SourceDoc(
        id='dga-controls-registration-domains-platforms-services-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Controls for Registration and Management of Digital Government Domains, Platforms, and Services',
        title_ar='ضوابط تسجيل وإدارة نطاقات ومنصات وخدمات الحكومة الرقمية',
        url='https://dga.gov.sa/sites/default/files/2025-08/Controls%20for%20Registration%20and%20Management%20of%20Digital%20Government%20Domains%2C%20Platforms%2C%20and%20Services-V1.0.pdf',
        landing_url='https://dga.gov.sa/en/regulatory-documents/registration-management-domains-platforms-digital-government-services',
        version='1.0',
        published_date='2024',
        language='en',
        category='digital_government_controls',
    ),
    SourceDoc(
        id='dga-controls-digital-content-quality-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Controls for Improving the Quality of Digital Content for Government Websites and Digital Platforms',
        title_ar='ضوابط تحسين جودة المحتوى الرقمي للمواقع والمنصات الحكومية',
        url='https://dga.gov.sa/sites/default/files/2025-08/Controls%20for%20Improving%20the%20Quality%20of%20Digital%20Content%20for%20Government%20Websites%20and%20Digital%20Platforms%20to%20Enhance%20Their%20Visibility%20on%20Search%20Engines-V1.0.pdf',
        landing_url='https://dga.gov.sa/en/regulatory-documents/improve-gov-digital-content-visibility',
        version='1.0',
        published_date='2024',
        language='en',
        category='digital_government_controls',
    ),
    SourceDoc(
        id='dga-controls-risk-business-continuity-v4',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Controls of Risk Management and Business Continuity for Digital Government',
        title_ar='ضوابط إدارة المخاطر واستمرارية الأعمال للحكومة الرقمية',
        url='https://dga.gov.sa/sites/default/files/2025-09/Controls%20of%20Risk%20Management%20and%20Business%20Continuity%20for%20Digital%20Government-V4.0.pdf',
        landing_url='https://dga.gov.sa/en/Controls_Of_Risk_and_Business_Continuity_Management_For_Digital_Government',
        version='4.0',
        published_date='2025',
        language='en',
        category='digital_government_controls',
    ),
    SourceDoc(
        id='dga-controls-whole-of-government-platforms-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Controls for Whole of Government Platforms',
        title_ar='ضوابط المنصات الحكومية الشاملة',
        url='https://dga.gov.sa/sites/default/files/2023-05/Controls%20for%20Whole%20of%20Government%20Platforms%20%E2%80%93%20V1.0_0.pdf',
        landing_url='https://dga.gov.sa/en/Controls_of_Whole_of_Government_Platforms',
        version='1.0',
        published_date='2023',
        language='en',
        category='digital_government_controls',
    ),
    SourceDoc(
        id='dga-standards-qualification-revenue-sharing-v2',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Standards and Procedures for Qualifying to Engage in Digital Government Work (Revenue-Sharing)',
        title_ar='معايير وإجراءات التأهيل للعمل في الحكومة الرقمية من خلال نموذج تقاسم الإيرادات',
        url='https://dga.gov.sa/sites/default/files/2026-06/Standards-procedures-for-qualifying-to-engage-in-digital-government-work-through-the-revenue-sharing-model-V2.0.pdf',
        landing_url='https://dga.gov.sa/en/regulatory-documents/standards-qualification-procedures-digital-government',
        version='2.0',
        published_date='2025',
        language='en',
        category='digital_government_standards',
    ),
    SourceDoc(
        id='dga-e-participation-controls-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='E-Participation Controls',
        title_ar='ضوابط المشاركة الإلكترونية',
        url='https://dga.gov.sa/sites/default/files/2023-07/%20E-Participation%20Controls%20%E2%80%93%20V1.0.pdf',
        landing_url='https://dga.gov.sa/en/E-Participation-Controls',
        version='1.0',
        published_date='2024',
        language='en',
        category='digital_government_controls',
    ),
    SourceDoc(
        id='dga-controls-awarding-projects-revenue-sharing-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Controls for Awarding Digital Government Projects (Revenue-Sharing Model)',
        title_ar='ضوابط إسناد مشاريع الحكومة الرقمية وفق نموذج تقاسم الإيرادات',
        url='https://dga.gov.sa/sites/default/files/2026-06/Controls%20for%20Awarding%20Digital%20Government%20Projects%20according%20to%20Revenue-Sharing%20Model-V1_1.pdf',
        landing_url='https://dga.gov.sa/en/regulatory-documents/controls-regulating-governing-digital-government-work',
        version='1.0',
        published_date='2026',
        language='en',
        category='digital_government_controls',
    ),
    SourceDoc(
        id='dga-enterprise-architecture-establishment-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Enterprise Architecture Establishment for Government Entities',
        title_ar='إنشاء البنية المؤسسية للجهات الحكومية',
        url='https://dga.gov.sa/sites/default/files/2022-11/Enterprise%20Architecture%20Establishment%20for%20Government%20Entities%20-%20V1.0.pdf',
        landing_url='https://dga.gov.sa/en/Enterprise_Architecture_Establishment_for_Government_Entities',
        version='1.0',
        published_date='2022',
        language='en',
        category='enterprise_architecture',
    ),
    SourceDoc(
        id='dga-national-enterprise-architecture-methodology-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Guideline for Implementing the National Enterprise Architecture Methodology',
        title_ar='دليل تطبيق منهجية البنية المؤسسية الوطنية',
        url='https://dga.gov.sa/sites/default/files/2026-03/Guideline%20for%20Implementing%20the%20National%20Enterprise%20Architecture%20Methodology-V1.pdf',
        landing_url='https://dga.gov.sa/en/regulatory-documents/guideline-national-enterprise-architecture-methodology',
        version='1.0',
        published_date='2026',
        language='en',
        category='enterprise_architecture',
    ),
    SourceDoc(
        id='dga-cloud-computing-adoption-guideline-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Guideline for Cloud Computing Adoption by Government Agencies',
        title_ar='دليل تبني الحوسبة السحابية للجهات الحكومية',
        url='https://dga.gov.sa/sites/default/files/2023-09/Guideline%20for%20Cloud%20Computing%20Adoption%20by%20Government%20Agencies%20%E2%80%93%20V1.0.pdf',
        landing_url='https://dga.gov.sa/en/Cloud-Computing-Adoption-by-Government-Agencies',
        version='1.0',
        published_date='2023',
        language='en',
        category='cloud_computing',
    ),
    SourceDoc(
        id='dga-api-guideline-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Guideline of Application Programming Interfaces (APIs)',
        title_ar='دليل واجهات برمجة التطبيقات',
        url='https://dga.gov.sa/sites/default/files/2024-02/Guideline%20of%20Application%20Programming%20Interfaces%20%28APIs%29.pdf',
        landing_url='https://dga.gov.sa/en/Guideline-Application-Programming-Interfaces',
        version='1.0',
        published_date='2023',
        language='en',
        category='interoperability_api',
    ),
    SourceDoc(
        id='dga-definitions-guide-digital-platforms-products-services-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Introductory Guide to Digital Platforms, Products, and Services',
        title_ar='الدليل التعريفي للمنصات والمنتجات والخدمات الرقمية',
        url='https://dga.gov.sa/sites/default/files/2022-11/Introductory%20Guide%20to%20digital%20platforms%2C%20products%2C%20and%20services%20-%20V1.0.pdf',
        landing_url='https://dga.gov.sa/en/Definitions_Guide_of_Digital_Platforms_Products_and_Services',
        version='1.0',
        published_date='2022',
        language='en',
        category='digital_government_guideline',
    ),
    SourceDoc(
        id='dga-digital-experience-maturity-index-2026-v5',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Introductory Guideline of Digital Experience Maturity Index for Government Services 2026',
        title_ar='الدليل التعريفي لمؤشر نضج التجربة الرقمية للخدمات الحكومية 2026',
        url='https://dga.gov.sa/sites/default/files/2026-02/Introductory%20Guideline%20of%20Digital%20Experience%20Maturity%20Index%20for%20Government%20Services%202026-V5.0.pdf',
        landing_url='https://dga.gov.sa/en/regulatory-documents/guideline-digital-experience-maturity-index-government-services-2026',
        version='5.0',
        published_date='2026',
        language='en',
        category='maturity_assessment',
    ),
    SourceDoc(
        id='dga-standards-digital-transformation-v1',
        authority='DGA',
        authority_name_ar='هيئة الحكومة الرقمية',
        title_en='Standards of Digital Transformation (V1.0)',
        title_ar='معايير التحول الرقمي',
        url='https://dga.gov.sa/sites/default/files/2024-02/Standards%20Digital%20Transformation%20V1.0%20.pdf',
        landing_url='https://dga.gov.sa/en/Standards_Of_Digital_Transformation-old',
        version='1.0',
        published_date='2023',
        language='en',
        category='digital_government_standards',
    ),
    # ===================== NDMO — National Data Management Office =====================
    SourceDoc(
        id='ndmo-data-governance-policies-en',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='National Data Governance Interim Regulations & Policies',
        title_ar='السياسات واللوائح التنظيمية لإدارة البيانات الوطنية',
        url='https://sdaia.gov.sa/ndmo/Files/PoliciesEn.pdf',
        landing_url='https://sdaia.gov.sa/ndmo/',
        version='1.0',
        published_date='2020-06',
        language='en',
        category='data_governance_framework',
    ),
    SourceDoc(
        id='ndmo-data-governance-policies-ar',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='National Data Governance Interim Regulations & Policies — Arabic',
        title_ar='السياسات واللوائح التنظيمية لإدارة البيانات الوطنية',
        url='https://sdaia.gov.sa/ndmo/Files/PoliciesAr.pdf',
        landing_url='https://sdaia.gov.sa/ndmo/',
        version='1.0',
        published_date='2020-06',
        language='ar',
        category='data_governance_framework',
    ),
    SourceDoc(
        id='ndmo-data-management-standards-en',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='Data Management and Personal Data Protection Standards',
        title_ar='معايير إدارة البيانات وحماية البيانات الشخصية',
        url='https://sdaia.gov.sa/en/SDAIA/about/Documents/DataManagementPersonalDataProtectionStandards.pdf',
        landing_url='https://sdaia.gov.sa/en/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.5',
        published_date='2020',
        language='en',
        category='data_management_standards',
    ),
    SourceDoc(
        id='ndmo-data-management-standards-ar',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='Data Management and Personal Data Protection Standards',
        title_ar='معايير إدارة البيانات وحماية البيانات الشخصية',
        url='https://sdaia.gov.sa/ar/SDAIA/about/Documents/DataManagementPersonalDataProtectionStandardsAr.pdf',
        landing_url='https://sdaia.gov.sa/ar/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.5',
        published_date='2020',
        language='ar',
        category='data_management_standards',
    ),
    SourceDoc(
        id='ndmo-data-classification-en',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='Data Classification Policy',
        title_ar='سياسة تصنيف البيانات',
        url='https://sdaia.gov.sa/en/SDAIA/about/Documents/DataClassificationPolicy.pdf',
        landing_url='https://sdaia.gov.sa/en/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.0',
        published_date='2020',
        language='en',
        category='data_classification',
    ),
    SourceDoc(
        id='ndmo-data-classification-ar',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='Data Classification Policy',
        title_ar='سياسة تصنيف البيانات',
        url='https://sdaia.gov.sa/ar/SDAIA/about/Documents/DataClassificationPolicyAr.pdf',
        landing_url='https://sdaia.gov.sa/ar/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.0',
        published_date='2020',
        language='ar',
        category='data_classification',
    ),
    SourceDoc(
        id='ndmo-data-sharing-en',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='Data Sharing Policy',
        title_ar='سياسة مشاركة البيانات',
        url='https://sdaia.gov.sa/en/SDAIA/about/Documents/DataSharingPolicyEN.pdf',
        landing_url='https://sdaia.gov.sa/en/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.0',
        published_date='2020',
        language='en',
        category='data_sharing',
    ),
    SourceDoc(
        id='ndmo-data-sharing-ar',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='Data Sharing Policy',
        title_ar='سياسة مشاركة البيانات',
        url='https://sdaia.gov.sa/ar/SDAIA/about/Documents/DataSharingPolicyAR.pdf',
        landing_url='https://sdaia.gov.sa/ar/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.0',
        published_date='2020',
        language='ar',
        category='data_sharing',
    ),
    SourceDoc(
        id='ndmo-open-data-en',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='Open Data Policy',
        title_ar='سياسة البيانات المفتوحة',
        url='https://sdaia.gov.sa/en/SDAIA/about/Documents/OpenDataPolicy.pdf',
        landing_url='https://sdaia.gov.sa/en/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.0',
        published_date='2020',
        language='en',
        category='open_data',
    ),
    SourceDoc(
        id='ndmo-open-data-ar',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='Open Data Policy',
        title_ar='سياسة البيانات المفتوحة',
        url='https://sdaia.gov.sa/ar/SDAIA/about/Documents/OpenDataPolicyAr.pdf',
        landing_url='https://sdaia.gov.sa/ar/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.0',
        published_date='2020',
        language='ar',
        category='open_data',
    ),
    SourceDoc(
        id='sdaia-ai-ethics-en',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='AI Ethics Principles',
        title_ar='مبادئ أخلاقيات الذكاء الاصطناعي',
        url='https://sdaia.gov.sa/en/SDAIA/about/Documents/ai-principles.pdf',
        landing_url='https://sdaia.gov.sa/en/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='2.0',
        published_date='2025',
        language='en',
        category='ai_ethics',
    ),
    SourceDoc(
        id='sdaia-ai-ethics-ar',
        authority='NDMO',
        authority_name_ar='مكتب إدارة البيانات الوطنية',
        title_en='AI Ethics Principles',
        title_ar='مبادئ أخلاقيات الذكاء الاصطناعي',
        url='https://sdaia.gov.sa/ar/SDAIA/about/Documents/ai-principles.pdf',
        landing_url='https://sdaia.gov.sa/ar/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='2.0',
        published_date='2025',
        language='ar',
        category='ai_ethics',
    ),
    # ===================== PDPL — Personal Data Protection Law (SDAIA) =====================
    SourceDoc(
        id='pdpl-law-en',
        authority='PDPL',
        authority_name_ar='نظام حماية البيانات الشخصية',
        title_en='Personal Data Protection Law (PDPL)',
        title_ar='نظام حماية البيانات الشخصية',
        url='https://sdaia.gov.sa/en/SDAIA/about/Documents/PersonalDataProtectionLaw.pdf',
        landing_url='https://sdaia.gov.sa/en/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='2.0',
        published_date='2023',
        language='en',
        category='data_protection_law',
    ),
    SourceDoc(
        id='pdpl-law-ar',
        authority='PDPL',
        authority_name_ar='نظام حماية البيانات الشخصية',
        title_en='Personal Data Protection Law (PDPL)',
        title_ar='نظام حماية البيانات الشخصية',
        url='https://sdaia.gov.sa/ar/SDAIA/about/Documents/PersonalDataProtectionLawAr.pdf',
        landing_url='https://sdaia.gov.sa/ar/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='2.0',
        published_date='2023',
        language='ar',
        category='data_protection_law',
    ),
    SourceDoc(
        id='pdpl-implementing-regulations-en',
        authority='PDPL',
        authority_name_ar='نظام حماية البيانات الشخصية',
        title_en='Implementing Regulation of the Personal Data Protection Law',
        title_ar='اللائحة التنفيذية لنظام حماية البيانات الشخصية',
        url='https://sdaia.gov.sa/en/SDAIA/about/Documents/ImplementingRegulationPersonalDataProtectionLaw.pdf',
        landing_url='https://sdaia.gov.sa/en/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.0',
        published_date='2023',
        language='en',
        category='pdpl_implementing_regulations',
    ),
    SourceDoc(
        id='pdpl-implementing-regulations-ar',
        authority='PDPL',
        authority_name_ar='نظام حماية البيانات الشخصية',
        title_en='Implementing Regulation of the Personal Data Protection Law',
        title_ar='اللائحة التنفيذية لنظام حماية البيانات الشخصية',
        url='https://sdaia.gov.sa/ar/SDAIA/about/Documents/ImplementingRegulationPersonalDataProtectionLawAr.pdf',
        landing_url='https://sdaia.gov.sa/ar/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.0',
        published_date='2023',
        language='ar',
        category='pdpl_implementing_regulations',
    ),
    SourceDoc(
        id='pdpl-data-transfer-regulation-en',
        authority='PDPL',
        authority_name_ar='نظام حماية البيانات الشخصية',
        title_en='Regulation on Personal Data Transfer Outside the Kingdom',
        title_ar='لائحة نقل البيانات الشخصية إلى خارج المملكة',
        url='https://sdaia.gov.sa/Documents/RegulationonPersonalDataEN.pdf',
        landing_url='https://sdaia.gov.sa/en/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.0',
        published_date='2024',
        language='en',
        category='data_transfer_regulation',
    ),
    SourceDoc(
        id='pdpl-data-transfer-regulation-ar',
        authority='PDPL',
        authority_name_ar='نظام حماية البيانات الشخصية',
        title_en='Regulation on Personal Data Transfer Outside the Kingdom',
        title_ar='لائحة نقل البيانات الشخصية إلى خارج المملكة',
        url='https://sdaia.gov.sa/Documents/RegulationonPersonalDataAR.pdf',
        landing_url='https://sdaia.gov.sa/ar/SDAIA/about/Pages/RegulationsAndPolicies.aspx',
        version='1.0',
        published_date='2024',
        language='ar',
        category='data_transfer_regulation',
    ),
    # ===================== CST — Communications, Space & Technology Commission =====================
    SourceDoc(
        id='cst-crf-en',
        authority='CST',
        authority_name_ar='هيئة الاتصالات والفضاء والتقنية',
        title_en='Cybersecurity Regulatory Framework (CRF) for the ICT Sector',
        title_ar='الإطار التنظيمي للأمن السيبراني لمقدمي الخدمة في قطاع الاتصالات وتقنية المعلومات',
        url='https://www.cst.gov.sa/-/media/D10AB7DF05CC45CAB78FC1136C405CCE.pdf',
        landing_url='https://www.cst.gov.sa/en/regulations-and-licenses/regulations/Document-413',
        version='1.0',
        published_date='2020',
        language='en',
        category='telecom_cybersecurity_framework',
    ),
    SourceDoc(
        id='cst-crf-ar',
        authority='CST',
        authority_name_ar='هيئة الاتصالات والفضاء والتقنية',
        title_en='Cybersecurity Regulatory Framework (CRF) for the ICT Sector',
        title_ar='الإطار التنظيمي للأمن السيبراني لمقدمي الخدمة في قطاع الاتصالات وتقنية المعلومات',
        url='https://www.cst.gov.sa/-/media/EBC4F418A9F24586B095713014AE9AB6.pdf',
        landing_url='https://www.cst.gov.sa/ar/regulations-and-licenses/regulations/Document-413',
        version='1.0',
        published_date='2020',
        language='ar',
        category='telecom_cybersecurity_framework',
    ),
    SourceDoc(
        id='cst-cloud-en',
        authority='CST',
        authority_name_ar='هيئة الاتصالات والفضاء والتقنية',
        title_en='Cloud Computing Services Provisioning Regulations',
        title_ar='تنظيمات تقديم خدمات الحوسبة السحابية',
        url='https://www.cst.gov.sa/-/media/9D1462BB90C7465AA4797D87DABB4F5B.pdf',
        landing_url='https://www.cst.gov.sa/en/regulations-and-licenses/regulations/Document-1550',
        version='1.0',
        published_date='2023',
        language='en',
        category='cloud_computing_regulation',
    ),
    SourceDoc(
        id='cst-cloud-ar',
        authority='CST',
        authority_name_ar='هيئة الاتصالات والفضاء والتقنية',
        title_en='Cloud Computing Services Provisioning Regulations',
        title_ar='تنظيمات تقديم خدمات الحوسبة السحابية',
        url='https://www.cst.gov.sa/-/media/7B782FB178C14472B837FED5520A4718.pdf',
        landing_url='https://www.cst.gov.sa/ar/regulations-and-licenses/regulations/Document-1550',
        version='1.0',
        published_date='2023',
        language='ar',
        category='cloud_computing_regulation',
    ),
    SourceDoc(
        id='cst-pdp-en',
        authority='CST',
        authority_name_ar='هيئة الاتصالات والفضاء والتقنية',
        title_en='General Principles for Personal Data Protection',
        title_ar='المبادئ العامة لحماية البيانات الشخصية',
        url='https://www.cst.gov.sa/-/media/51C9F3CDC7C24E498A1A69FB30C0C41E.pdf',
        landing_url='https://www.cst.gov.sa/en/regulations-and-licenses/regulations/Document-404',
        version='1.0',
        published_date='2020',
        language='en',
        category='data_protection_regulation',
    ),
    SourceDoc(
        id='cst-pdp-ar',
        authority='CST',
        authority_name_ar='هيئة الاتصالات والفضاء والتقنية',
        title_en='General Principles for Personal Data Protection',
        title_ar='المبادئ العامة لحماية البيانات الشخصية',
        url='https://www.cst.gov.sa/-/media/B5EC60E0BF3441A6A44BFF297E1F94AD.pdf',
        landing_url='https://www.cst.gov.sa/ar/regulations-and-licenses/regulations/Document-404',
        version='1.0',
        published_date='2020',
        language='ar',
        category='data_protection_regulation',
    ),
    SourceDoc(
        id='cst-iot-en',
        authority='CST',
        authority_name_ar='هيئة الاتصالات والفضاء والتقنية',
        title_en='IoT Regulations',
        title_ar='تنظيمات إنترنت الأشياء',
        url='https://www.cst.gov.sa/-/media/19D08953A8754EEEA3CA8AF83F2E871D.pdf',
        landing_url='https://www.cst.gov.sa/en/regulations-and-licenses/regulations/Document-1602',
        version='1.0',
        published_date='2024',
        language='en',
        category='iot_regulation',
    ),
    SourceDoc(
        id='cst-iot-ar',
        authority='CST',
        authority_name_ar='هيئة الاتصالات والفضاء والتقنية',
        title_en='IoT Regulations',
        title_ar='تنظيمات إنترنت الأشياء',
        url='https://www.cst.gov.sa/-/media/BC4437E8066B4D0F8BDC619D641E77D5.pdf',
        landing_url='https://www.cst.gov.sa/ar/regulations-and-licenses/regulations/Document-1602',
        version='1.0',
        published_date='2024',
        language='ar',
        category='iot_regulation',
    ),

]

AUTHORITIES = {
    "DGA": {"name_en": "Digital Government Authority", "name_ar": "هيئة الحكومة الرقمية"},
    "NCA": {"name_en": "National Cybersecurity Authority", "name_ar": "الهيئة الوطنية للأمن السيبراني"},
    "NDMO": {"name_en": "National Data Management Office", "name_ar": "مكتب إدارة البيانات الوطنية"},
    "PDPL": {"name_en": "Personal Data Protection Law", "name_ar": "نظام حماية البيانات الشخصية"},
    "CST": {"name_en": "Communications, Space & Technology Commission", "name_ar": "هيئة الاتصالات والفضاء والتقنية"},
}


def load_sources() -> List[SourceDoc]:
    """Registry + optional external JSON overrides (for adding authorities without code)."""
    sources = list(REGISTRY)
    extra = os.environ.get("KB_SOURCES_FILE")
    if extra and os.path.exists(extra):
        with open(extra, encoding="utf-8") as f:
            for d in json.load(f):
                sources.append(SourceDoc(**d))
    return sources
