"""knowledge base tables

Revision ID: a6e498d454ed
Revises: c5bb0fe61e4e
Create Date: 2026-07-13 18:00:08.938381
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a6e498d454ed'
down_revision: Union[str, None] = 'c5bb0fe61e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('authority', sa.String(length=32), nullable=False),
    sa.Column('title_en', sa.String(length=512), nullable=False),
    sa.Column('title_ar', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('published_date', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('landing_url', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_path', sa.String(length=1024), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=512), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_documents_authority'), ['authority'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_documents_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_documents_source_id'), ['source_id'], unique=False)

    op.create_table('kb_ingestion_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kb_ingestion_runs')
    with op.batch_alter_table('kb_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_kb_documents_file_hash'))
        batch_op.drop_index(batch_op.f('ix_kb_documents_authority'))

    op.drop_table('kb_documents')
    # ### end Alembic commands ###
